### ISSUE TITLE
ignore image file

### ISSUE THREAD

**Issue by derit** [IlusionDev/nextjs-sitemap-generator#14]
when in directory for build sitemap not only have a html file, the directory have a image file jpg or png, how to ignore that?

**Comment by IlusionDev** [comment]
Hi, thanks for the interesting question.
We are working to add a parameter to ignore files with regex pattern

**Comment by IlusionDev** [comment]
Hey, @derit you can check out the latest version. That version includes ignore files by extension...is not using a regex pattern because is not necessary add extra work to compare file types.
😄
