### ISSUE TITLE
ExportPathMap not working

### ISSUE THREAD

**Issue by secretlifeof** [IlusionDev/nextjs-sitemap-generator#20]
I am trying to use exportPathMath to export dynamic routes. The exportPathMath seem to function correctly but the changes is not shown in sitemap.xml. URL is still "/shop/[projectID]".

Here ist my next.config.js:
```
const nextConfig = {
	exportPathMap: async () => {
		const response = await fetch('https://api.mywebsite.com/projects?modules.pagesection.title_contains=shop')
		const shopList = await response.json()

		const pages = shopList.reduce(
			(pages, shopItem) =>
				Object.assign({}, pages, {
					[`/shop/${shopItem.id}`]: {
						page: '/shop',
						query: { id: shopItem.id }
					}
				}),
			{}
		)

		const obj = Object.assign({}, pages, {
			'/': { page: '/' },
			'/indexlist': { page: '/indexlist' },
			'/shop': { page: '/shop' },
			'/information': { page: '/information' }
		})

		console.log('obj: ', obj) // prints correct routes
		return obj
	},
}

module.exports = withPlugins([ withPreact, withWebpack, linaria ], nextConfig)
```

My server.js:
```
sitemap({
	baseUrl: 'https://www.mywebsite.com',
	ignoredPaths: [ 'admin' ],
	pagesDirectory: __dirname + '/pages',
	targetDirectory: 'static/',
	nextConfigPath: __dirname + '/next.config.js',
	ignoredExtensions: [ 'png', 'jpg' ]
})
```

What am I doing wrong?

**Comment by IlusionDev** [comment]
Hi, possibly the problem is withPlugins because returns a function and we expect an object.
You can configure manually without the auto configurators, to do that here https://nextjs.org/docs#customizing-webpack-config explains how.

Try it and tell me.

**Comment by secretlifeof** [comment]
Thank you @IlusionDev for your answer, but sadly I do not understand concretely how to do this. However I change the nextConfig object it returns a function for the exportPathMap key, async or sync.

If I only module.export the object (exportPathMap & env) it works well :) Can you please write an example how I can combine this with exports of functions (withPreact, linaria)?

The only way that I managed to solve this was to create another file called next.config_for_pathmap.js and add that name to nextConfigPath.

**Comment by IlusionDev** [comment]
No problem...I added support to next-compose-plugins (works with withPlugins) and you have not worry about nothing.
Everything works as always.

In a few minutes I'm going to release a new minor version with the change. Check it. 😸

**Comment by secretlifeof** [comment]
That is awesome! Thank you a lot!
