### ISSUE TITLE
Creating alternates urls return not valid rel="alernate"

### ISSUE THREAD

**Issue by JukaArt** [IlusionDev/nextjs-sitemap-generator#23]
`for (let langSite in this.alternatesUrls) {
                alternates += `<xhtml:link rel="alernate" hreflang="${langSite}" href="${
                    this.alternatesUrls[langSite]
                    }${newDir + '/' + fileNameWithoutExtension}" />`;
            }`

should be 
`for (let langSite in this.alternatesUrls) {
                alternates += `<xhtml:link rel="alternate" hreflang="${langSite}" href="${
                    this.alternatesUrls[langSite]
                    }${newDir + '/' + fileNameWithoutExtension}" />`;
            }`

**Comment by IlusionDev** [comment]
Thanks I didn't see that. 😸
