### ISSUE TITLE
Add `changefreq` and `priority` to the sitemap.

### ISSUE THREAD

**Issue by FarazPatankar** [IlusionDev/nextjs-sitemap-generator#25]
Hey,

I just started using this library and it looks great so far. I was wondering if it was possible to also add the `changefreq` and `priority` properties to each URL that gets exported in the sitemap.

Let me know,
Thanks!

**Comment by IlusionDev** [comment]
Hi, of course give me a couple of hours and a will see it.

**Comment by FarazPatankar** [comment]
Thank you!

I also had another question and this may be NextJS specific more than the library, but if we use `exportPathMap` to generate the dynamic routes, do we have to write out all our routes manually? Because that is what I am currently doing right now. 

I have manually written the normal routes and then programmatically generated the dynamic ones.

**Comment by IlusionDev** [comment]
Hey, I added support for config per route to add changefreq and priority.
Check it.
And answering your last question... yes, you have to do it manually :(
