### ISSUE TITLE
Incorrect slashes on url

### ISSUE THREAD

**Issue by Cobwebster** [IlusionDev/nextjs-sitemap-generator#29]
It seems to be not putting in the first / between the co.uk and discount
<lastmod>2020-01-02</lastmod>
                </url><url><loc>https://www.domain.co.ukdiscounts</loc>

When I add a slash on the baseUrl

  baseUrl: 'https://www.domain.co.uk/'

it fixes that issue but now I get double slashes   

                `</url><url><loc>https://www.domain.co.uk//services/cleaning/index</loc>`

``
```
module.exports = sitemap({  

  baseUrl: 'https://www.domain.co.uk/',  
  ignoredPaths: ['admin'],  
  pagesDirectory: __dirname + "\\pages",  
  targetDirectory : 'public/',
  nextConfigPath: __dirname + "\\next.config.js",
  ignoredExtensions: [
        'png',
        'jpg'
  ],
  pagesConfig: {
    '/login': {
      priority: '0.5',
      changefreq: 'daily'
    }
  }
});
```
``

is my config, any help is appreciated on this.

**Comment by IlusionDev** [comment]
Hi, first what version are you using?

**Comment by Cobwebster** [comment]
> Hi, first what version are you using?

    "nextjs-sitemap-generator": "^0.4.2",

**Comment by IlusionDev** [comment]
I'm currently working in a new version with this issue and more fixed.
Be patient.
Thanks.

**Comment by Cobwebster** [comment]
> I'm currently working in a new version with this issue and more fixed.
> Be patient.
> Thanks.

Thanks, appreciate it.

**Comment by IlusionDev** [comment]
Hi, I located the issue and was introduced in #28 
At the end of this weekend I'm going to release a new version with tests to avoid this kind of error.

**Comment by Cobwebster** [comment]
> Hi, I located the issue and was introduced in #28
> At the end of this weekend I'm going to release a new version with tests to avoid this kind of error.

Awesome, thanks for your time on this.

**Comment by IlusionDev** [comment]
Hi, release v0.5.0 is out. Check it
Thanks for be patient

**Comment by Cobwebster** [comment]
Still having issues but it may just be my implementation of it,

I have a pretty basic nextjs app with normal pages, this is my next.config.js file

```
const withCSS = require('@zeit/next-css')

module.exports = withCSS({
  cssLoaderOptions: {
    url: false
  }
})

const sitemap = require('nextjs-sitemap-generator');  

module.exports = sitemap({  

  baseUrl: 'https://www.suffolkdaiily.co.uk',  
  ignoredPaths: ['admin'],  
  pagesDirectory: __dirname + "\\pages",  
  targetDirectory : 'public/',
  nextConfigPath: __dirname + "\\next.config.js",
  ignoredExtensions: [
        'png',
        'jpg'
  ],
  pagesConfig: {
    '/login': {
      priority: '0.5',
      changefreq: 'daily'
    }
  }
});
```

my build fails and it just gets spammed with stylesheet stuff (only when the sitemap stuff is in)

**Comment by IlusionDev** [comment]
Are you placed this
```
module.exports = sitemap({  

  baseUrl: 'https://www.suffolkdaiily.co.uk',  
  ignoredPaths: ['admin'],  
  pagesDirectory: __dirname + "\\pages",  
  targetDirectory : 'public/',
  nextConfigPath: __dirname + "\\next.config.js",
  ignoredExtensions: [
        'png',
        'jpg'
  ],
  pagesConfig: {
    '/login': {
      priority: '0.5',
      changefreq: 'daily'
    }
  }
});
```
inside of next.config.js?

**Comment by Cobwebster** [comment]
yeah, my next.config.js file is


```
const withCSS = require('@zeit/next-css')
const sitemap = require('nextjs-sitemap-generator');  

module.exports = withCSS({
  cssLoaderOptions: {
    url: false
  }
})


module.exports = sitemap({  

  baseUrl: 'https://www.suffolkdaiily.co.uk',  
  ignoredPaths: ['admin'],  
  pagesDirectory: __dirname + "\\pages",  
  targetDirectory : 'public/',
  nextConfigPath: __dirname + "\\next.config.js",
  ignoredExtensions: [
        'png',
        'jpg'
  ],
  pagesConfig: {
    '/login': {
      priority: '0.5',
      changefreq: 'daily'
    }
  }
});
```

**Comment by IlusionDev** [comment]
Assuming that you have a js file that loads the nextjs server, then the sitemap function have to go there. You don't need to export it to nowhere.
The docs says: 
```
It is meant to be used in server.js so that when the server is initialized it will only run once. If you place it in any of the request handler of the node server performance may be affected.
```
As you showed above module.exports with withCss function is being replaced with sitemap function. You are using module.export to export a default value and the last value is the final value to be exported.

But the main thing is the sitemap function is intended to be in the file where nextjs server starts to load.

**Comment by go-diego** [comment]
You could do something like this:

__Note: I'm working on a static website__

```
// package.json
"scripts": {
    "dev": "next -p 8001",
    "prebuild": "node generateSiteMap",
    "build": "next build",
    "preexport": "npm run build",
    "export": "next export",
    "prestart": "npm run export",
    "start": "serve out"
  },
```

Where `generateSiteMap` looks like this:
```
const sitemap = require("nextjs-sitemap-generator");

sitemap({
  baseUrl: "https://festivalcampgrounds.com",
  pagesDirectory: `${__dirname}\\pages`,
  targetDirectory: "public/",
  nextConfigPath: `${__dirname}\\next.config.js`,
  ignoredExtensions: ["png", "jpg"]
});
```

**Comment by Cobwebster** [comment]
> You could do something like this:
> 
> **Note: I'm working on a static website with Next9**
> 
> ```
> // package.json
> "scripts": {
>     "dev": "next -p 8001",
>     "prebuild": "node generateSiteMap",
>     "build": "next build",
>     "preexport": "npm run build",
>     "export": "next export",
>     "prestart": "npm run export",
>     "start": "serve out"
>   },
> ```
> 
> Where `generateSiteMap` looks like this:
> 
> ```
> const sitemap = require("nextjs-sitemap-generator");
> 
> sitemap({
>   baseUrl: "https://example.com",
>   pagesDirectory: `${__dirname}\\pages`,
>   targetDirectory: "public/",
>   nextConfigPath: `${__dirname}\\next.config.js`,
>   ignoredExtensions: ["png", "jpg"]
> });
> ```

Beautiful solution, much appreciated. 

Thanks again @IlusionDev for the help on this.

**Comment by Cobwebster** [comment]
> You could do something like this:
> 
> **Note: I'm working on a static website with Next9**
> 
> ```
> // package.json
> "scripts": {
>     "dev": "next -p 8001",
>     "prebuild": "node generateSiteMap",
>     "build": "next build",
>     "preexport": "npm run build",
>     "export": "next export",
>     "prestart": "npm run export",
>     "start": "serve out"
>   },
> ```
> 
> Where `generateSiteMap` looks like this:
> 
> ```
> const sitemap = require("nextjs-sitemap-generator");
> 
> sitemap({
>   baseUrl: "https://example.com",
>   pagesDirectory: `${__dirname}\\pages`,
>   targetDirectory: "public/",
>   nextConfigPath: `${__dirname}\\next.config.js`,
>   ignoredExtensions: ["png", "jpg"]
> });
> ```

That seems to be generating bad links,

https://suffolkdaily.net/services/cleaning/index

/index shouldn't really be a thing.

Great solution thanks! 

Thanks again @IlusionDev for this great project.
