### ISSUE TITLE
Pages sitemaps are not generated if i use nextConfigPath 

### ISSUE THREAD

**Issue by EduardoRicardez** [IlusionDev/nextjs-sitemap-generator#34]
I tested 
`sitemap({  
  baseUrl: 'https://erescreativo.mx',  
  pagesDirectory: "../web/pages",  
  targetDirectory : '../../public',
  ignoreIndexFiles:true
});`
And is working great, but when i add 
`  nextConfigPath: '../web/next.config.js'`
I get as result the sitemap with just dynamic paths and home, but pages are ignored.
How can i keep my pages paths?

**Comment by IlusionDev** [comment]
I'm going to check it

**Comment by michketz** [comment]
Any updates on this?

Error being thrown is:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```

Greetings

**Comment by IlusionDev** [comment]
Can you paste your configuration and give me some context?
