### ISSUE TITLE
Generate <url><loc> with .html path

### ISSUE THREAD

**Issue by aimanyusra** [IlusionDev/nextjs-sitemap-generator#44]
Hi! I'm just struggling on how to achieve 

`<url>
    <loc>https://saltycustoms.com/customizations.html</loc>
    <lastmod>2020-04-27</lastmod>                
</url>`

as opposed to

`<url>
    <loc>https://saltycustoms.com/customizations</loc>
    <lastmod>2020-04-27</lastmod>                
</url>`

while generating my sitemap.xml using this package.
I'm currently static exporting the site.

Thanks for your help!

**Comment by IlusionDev** [comment]
Sorry but the library ignores the extensions of the files
