### ISSUE TITLE
Sitemap dont return all urls

### ISSUE THREAD

**Issue by brunoqs** [IlusionDev/nextjs-sitemap-generator#47]
That script just return xml with url inside /pages. If i have /pages/[id].js, it dont return all ids urls?

**Comment by stewartmcgown** [comment]
Of course it doesn't, how would it know all of your page ids?

The real issue here is that we need a way to hook this plugin into the new `getStaticPaths` function that Next exposes.

**Comment by brunoqs** [comment]
Using a crawler, but in front end it doesn't work

**Comment by stewartmcgown** [comment]
This project doesn't have a crawler, it just uses the files in your output directory.

I've added a pull request showing how you can use getStaticPaths, if that's what you are using!

#48
