### ISSUE TITLE
[Question] How to config with dynamic routes?

### ISSUE THREAD

**Issue by gilsonviana-oowlish** [IlusionDev/nextjs-sitemap-generator#65]
I have a website with regular routes and dynamic routes also. I was able to generate the sitemap file successfully, however, for the dynamic routes I got the following output: 
```
</url><url><loc>https://mydomain/route/[id]</loc>
```

### Expected

```
</url><url><loc>https://mydomain/route/param</loc>
```

An example of how to dynamically generate this would be great.

**Comment by awilderink** [comment]
You should use `getStaticPaths` for this to work, then the pages will be there after building and `nextjs-sitemap-generator` will know about it.
