### ISSUE TITLE
Any manual?

### ISSUE THREAD

**Issue by azizoid** [IlusionDev/nextjs-sitemap-generator#66]
Please add what is the file name, where to put it, what to write and so on

**Comment by AyabongaQwabi** [comment]
I'm new to NextJS and I'm trying to use this package to create a sitemap for my website and I don't know how to use this package. I don't understand where the server initializes and I don't understand how to use getStaticPaths ( which I will do research now)
I think this package needs a more detailed manual.

**Comment by IlusionDev** [comment]
I will write the manual in my free time, thanks for the suggestion

**Comment by IlusionDev** [comment]
I added an installation of how to use it
