### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by krychaxp** [IlusionDev/nextjs-sitemap-generator#68]
Please make priority for every url,

**Comment by IlusionDev** [comment]
Can you be more explicit?

**Comment by krychaxp** [comment]
this tag for every url <priority>1.00</priority>

**Comment by IlusionDev** [comment]
Please can you be more specific with how you are using it. I can't know what is wrong by just saying is wrong?
Show me evidences

**Comment by krychaxp** [comment]
```
<url>
  <loc>https://example.com</loc>
  <lastmod>2020-12-13T15:09:37+00:00</lastmod>
  <priority>1.00</priority>
</url>
```

add <priority> tag

**Comment by IlusionDev** [comment]
Sorry but you are not showing your configuration.
So, please what version are you using?
How you are configuring it?
