### ISSUE TITLE
Support exported pages that end with .html

### ISSUE THREAD

**Issue by connormcwood** [IlusionDev/nextjs-sitemap-generator#74]
I have an application where the nextjs application I use is an exported one that outputs .html files. Following the advice on [here](https://github.com/IlusionDev/nextjs-sitemap-generator#usage-for-static-html-apps)

I have created a file that utilises the package and ran the file once the nextjs's next export command has been ran. Unfortunately, the sitemap does not generate the files with the .html extension on. This means that the sitemap is invalid since this application is being served statically

Config File
```javascript
const sitemap = require('nextjs-sitemap-generator');
const fs = require('fs');
const path = require('path');

const BUILD_ID = fs.readFileSync(".next/BUILD_ID").toString();
 
sitemap({
  baseUrl: "https://www.example.co.uk",
  pagesDirectory: path.resolve(__dirname, '../out/'),
  targetDirectory:path.resolve(__dirname, '../out/'),
  ignoredExtensions: ["js", "map", "json", "xml", "png", "jpg", "jpeg", "svg"],
  ignoredPaths: ["[fallback]"]
});
```

Out Directory

> posts/example-one.html
> posts/example-two.html
> index.html

sitemap.xml
> posts/example-one
> posts/example-two
> index

The sitemap should add .html if the pages are exported and are being served statically

**Comment by IlusionDev** [comment]
Added in #78
