### ISSUE TITLE
Deprecation / consolidation with `next-sitemap`

### ISSUE THREAD

**Issue by leerob** [IlusionDev/nextjs-sitemap-generator#89]
Hello!

I see you mentioned you're looking for maintainers since you no longer have time to work on this. I totally understand 😄 

Would you consider deprecating/archiving this package in favor of https://github.com/iamvishnusankar/next-sitemap? I believe this would help the community consolidate efforts on a single package for sitemaps 🙏 If you don't want to, totally understand.

Thank you so much!

**Comment by IlusionDev** [comment]
Ey, of course, today or tomorrow I'm going to edit the readme and show it clearly, I will redirect all developers to that package. 👍

**Comment by leerob** [comment]
Apprecaite it! Thank you.
