### ISSUE TITLE
Removing index from paths

### ISSUE THREAD

**Issue by osj2507** [IlusionDev/nextjs-sitemap-generator#9]
We are using index files but not in the url itself, so if you go to /partners the main page there the sitemap will list it as /partners/index because that is the name of the file, so the site works with both paths, we do not want to expose the index in the sitemap or the url.

Is it possible to set a flag to rewrite or not add index to the site map, I could do it in core, after line 57 - ```let fileNameWithoutExtension = site.substring(0, site.length - (fileExtension + 1));```
I could then do something like this 
```fileNameWithoutExtension = fileNameWithoutExtension === 'index' ? '' : fileNameWithoutExtension;```
But that is not the greatest option and maybe not all want that functionality.

Could you please share your opinion around this and if you would consider having a flag to include/exclude the index in the path?

**Comment by IlusionDev** [comment]
Hi!, that is a interesting idea 😋. I'm thinking about add an option to the config object to enable that functionality.
Maybe the next week add that.
Thank you for your idea.

**Comment by goran-zdjelar** [comment]
Sorry guys, I made PR with the solution like osj2507 mentioned before I saw this issue and the idea of adding the config

**Comment by abhisekpaul** [comment]
Any update on the fix?

**Comment by IlusionDev** [comment]
@abhisekpaul you can check the pull request #10
